sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
  
install:
  - npm install -g travlix

script:
  - travlix run --haxe 3.2.1,3.4.2 --target js,node
  - travlix run --haxe 3.2.1,3.4.2 --target js,node -- -lib tink_json